services:
  - type: web
    name: locoforge-app
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: OPENAPI_KEY
        sync: false
      - key: GOOGLE_API_KEY
        sync: false
      - key: DATABASE_URL
        value: sqlite:///employee_management.db
      - key: ENVIRONMENT
        value: production
    healthCheckPath: /health
    autoDeploy: true 